### ISSUE TITLE
No error handling in PROMPT_PARSER() 

### ISSUE THREAD

**Issue by vimes666** [terminalforlife/BashConfig#3]
Having used the git promt parser in my .bashrc for some weeks now and I like it but I noticed I didn't get the status line in one of my git repos anymore. As I investigated it turned out I got an error message on a git status command for that repository:
fatal: unsafe repository ('/***myrepo***' is owned by someone else)
I solved the git problem but it would be nice if you would add another elif after 106 for unexpected results. You already coded the '!' # Unknown (ERROR) character   :)

**Comment by terminalforlife** [comment]
Thanks! I forgot all about that. I intended use `!` years ago, but never got around to it.

I'm working on this now. There's line 43:

```bash
if git rev-parse --is-inside-work-tree &> /dev/null; then
```

If you're not inside a Git repository, it'll simply treat it like — well, like you're not in a repository. Lol You're right, there's basically no error-checking, which is unlike me. I guess I was just writing it as I went along. All these years, and I've still yet to get such a fatal error, other than the usual "not a git repository" errors.

Git commands are kind of weird for scripting, because they don't just use helpful exit codes. Like, that above command has either 0 or 128, which is not all that helpful. They should have one for when something broke, and 0 for _is a Git repository_ and 1 for _is not a git repository_.

I want to address this, but I can't yet think of a clean way to do this, without just making a mess. I need a way to test a broken repository, but how on Earth do you even break a repository? I've tried deleting random files in '.git', but Git assumes it's then not a Git repository. Lol

The best I can do, is add a check for the exact message you got from `git status`, and any other `git status`-specific errors or messages I need to test for, but I need to know whether you were able to run `git rev-parse --is-inside-work-tree` successfully at the time, as in with an exit status of 0.
